#python -m sec_classifiers.drebin.get_drebin_feature --dataset_dir /path/to/dataset_directory --feature_dir path/to/save/feature_directory/hashsmooth-drebin
#python -m sec_classifiers.drebin.drebin_test --dataset_dir /path/to/dataset_directory/drebin --dataset_name drebin --model "svm" --smooth "none" --cuda --epochs 200 --lr 0.01
#python -m sec_classifiers.drebin.drebin_test --dataset_dir /path/to/dataset_directory/drebin --dataset_name drebin --model "dnn" --smooth "none" --cuda --epochs 200 --lr 0.001
#python -m sec_classifiers.drebin.drebin_test --dataset_dir /path/to/dataset_directory/drebin --dataset_name drebin --model "svm" --smooth "random" --cuda --sub_k 16 --epochs 200 --lr 0.01
#python -m sec_classifiers.drebin.drebin_test --dataset_dir /path/to/dataset_directory/drebin --dataset_name drebin --model "dnn" --smooth "random" --cuda --sub_k 16 --epochs 200 --lr 0.001
#python -m sec_classifiers.drebin.drebin_test --dataset_dir /path/to/dataset_directory/drebin --dataset_name drebin --model "svm" --smooth "hash" --cuda --sub_k 16 --epochs 200 --lr 0.01
#python -m sec_classifiers.drebin.drebin_test --dataset_dir /path/to/dataset_directory/drebin --dataset_name drebin --model "dnn" --smooth "hash" --cuda --sub_k 16 --epochs 200 --lr 0.001

# CodeXGLUE clone detection
CUDA_VISIBLE_DEVICES=0 python run.py --output_dir=./saved_models --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_train --do_test --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 2>&1| tee train.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_random_models --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_train --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "random" --k_random=64 --n_sampling=10 --n_estimation=10000 --seed 123456 2>&1| tee train_random_64.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_random_models --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_test --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "random" --k_random=64 --n_sampling=100 --n_estimation=10000 --seed 123456 2>&1| tee test_random_64.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_random_models --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_certify --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "random" --k_random=64 --n_sampling=100 --n_estimation=10000 --n_examples=200 --seed 123456 2>&1| tee cert_random_64.log

CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_randdel_models --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_train --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "randdel" --k_random=64 --n_sampling=10 --n_estimation=10000 --seed 123456 2>&1| tee train_randdel_64.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_randdel_models --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_test --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "randdel" --k_random=64 --n_sampling=100 --n_estimation=10000 --seed 123456 2>&1| tee test_randdel_64.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_randdel_models --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_certify --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "randdel" --k_random=64 --n_sampling=100 --n_estimation=10000 --n_examples=200 --seed 123456 2>&1| tee cert_randdel_64.log

CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_hash_models --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_train --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "hash" --k_random=20 --n_sampling=10 --n_estimation=10000 --seed 123456 2>&1| tee train_hash_64.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_hash_models --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_test --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "hash" --k_random=20 --n_sampling=100 --n_estimation=10000 --seed 123456 2>&1| tee test_hash_64.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_hash_models --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_certify --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "hash" --k_random=30 --n_sampling=100 --n_estimation=10000 --n_examples=200 --seed 123456 2>&1| tee cert_hash_64.log

CUDA_VISIBLE_DEVICES=0 python attack.py --output_dir=./saved_models --model_type=roberta --config_name=microsoft/codebert-base  --csv_store_path ./attack_base_result_GA.csv --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --use_ga --base_model=microsoft/codebert-base-mlm  --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/test_sampled_0_500.txt --test_data_file=../dataset/test_sampled.txt --block_size 512 --eval_batch_size 32 --do_certify --smooth=none --n_examples=200 --seed 123456 2>&1| tee attack_none_GA.log
CUDA_VISIBLE_DEVICES=0 python attack.py --output_dir=./saved_random_models --model_type=roberta --config_name=microsoft/codebert-base  --csv_store_path ./attack_base_result_random_GA.csv --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --use_ga --base_model=microsoft/codebert-base-mlm  --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/test_sampled_0_500.txt --test_data_file=../dataset/test_sampled.txt --block_size 512 --eval_batch_size 32 --do_certify --smooth=random --k_random=64 --n_sampling=100 --n_examples=200 --seed 123456 2>&1| tee attack_random_GA.log
CUDA_VISIBLE_DEVICES=0 python attack.py --output_dir=./saved_randdel_models --model_type=roberta --config_name=microsoft/codebert-base  --csv_store_path ./attack_base_result_randdel_GA.csv --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --use_ga --base_model=microsoft/codebert-base-mlm  --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/test_sampled_0_500.txt --test_data_file=../dataset/test_sampled.txt --block_size 512 --eval_batch_size 32 --do_certify --smooth=randdel --k_random=64 --n_sampling=100 --n_examples=200 --seed 123456 2>&1| tee attack_randdel_GA.log
CUDA_VISIBLE_DEVICES=0 python attack.py --output_dir=./saved_hash_models --model_type=roberta --config_name=microsoft/codebert-base  --csv_store_path ./attack_base_result_GA.csv --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --use_ga --base_model=microsoft/codebert-base-mlm  --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/test_sampled_0_500.txt --test_data_file=../dataset/test_sampled.txt --block_size 512 --eval_batch_size 32 --do_certify --smooth=hash --k_random=20 --n_sampling=100 --n_examples=200 --seed 123456 2>&1| tee attack_hash_GA.log

CUDA_VISIBLE_DEVICES=0 python mhm_attack.py --output_dir=./saved_models --model_type=roberta --config_name=microsoft/codebert-base  --csv_store_path ./attack_base_result_mhm.csv --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --use_ga --base_model=microsoft/codebert-base-mlm  --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/test_sampled_0_500.txt --test_data_file=../dataset/test_sampled.txt --block_size 512 --eval_batch_size 32 --do_certify --smooth=none --n_examples=200 --seed 123456 2>&1| tee attack_none_mhm.log
CUDA_VISIBLE_DEVICES=0 python mhm_attack.py --output_dir=./saved_random_models --model_type=roberta --config_name=microsoft/codebert-base  --csv_store_path ./attack_base_result_random_mhm.csv --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --use_ga --base_model=microsoft/codebert-base-mlm  --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/test_sampled_0_500.txt --test_data_file=../dataset/test_sampled.txt --block_size 512 --eval_batch_size 32 --do_certify --smooth=random --k_random=64 --n_sampling=100 --n_examples=200 --seed 123456 2>&1| tee attack_random_mhm.log
CUDA_VISIBLE_DEVICES=0 python mhm_attack.py --output_dir=./saved_randdel_models --model_type=roberta --config_name=microsoft/codebert-base  --csv_store_path ./attack_base_result_randdel_mhm.csv --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --use_ga --base_model=microsoft/codebert-base-mlm  --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/test_sampled_0_500.txt --test_data_file=../dataset/test_sampled.txt --block_size 512 --eval_batch_size 32 --do_certify --smooth=randdel --k_random=64 --n_sampling=100 --n_examples=200 --seed 123456 2>&1| tee attack_randdel_mhm.log
CUDA_VISIBLE_DEVICES=0 python mhm_attack.py --output_dir=./saved_hash_models --model_type=roberta --config_name=microsoft/codebert-base  --csv_store_path ./attack_base_result_hash_mhm.csv --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --use_ga --base_model=microsoft/codebert-base-mlm  --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/test_sampled_0_500.txt --test_data_file=../dataset/test_sampled.txt --block_size 512 --eval_batch_size 32 --do_certify --smooth=hash --k_random=20 --n_sampling=100 --n_examples=200 --seed 123456 2>&1| tee attack_hash_mhm.log


# CodeXGLUE authorship classification
CUDA_VISIBLE_DEVICES=0 python run.py  --output_dir=./saved_models/ --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base  --number_labels 66 --do_train --do_test --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --epoch 30 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 2>&1| tee train_gcjpy.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_random_models/ --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_train --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --epoch 30 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "random" --k_random=128 --n_sampling=100 --n_estimation=10000 --seed 123456 2>&1| tee train_random_64.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_random_models/ --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_test --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --epoch 30 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "random" --k_random=128 --n_sampling=100 --n_estimation=10000 --seed 123456 2>&1| tee test_random_64.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_random_models/ --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_certify --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --epoch 30 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "random" --k_random=128 --n_sampling=100 --n_estimation=10000 --seed 123456 2>&1| tee cert_random_64.log