python -m sec_classifiers.drebin.get_drebin_feature --dataset_dir /path/to/dataset_directory --feature_dir path/to/save/feature_directory/hashsmooth-drebin
python -m sec_classifiers.drebin.drebin_test --dataset_dir /path/to/dataset_directory/drebin --dataset_name drebin --model "svm" --smooth "none" --cuda --epochs 200 --lr 0.01
python -m sec_classifiers.drebin.drebin_test --dataset_dir /path/to/dataset_directory/drebin --dataset_name drebin --model "dnn" --smooth "none" --cuda --epochs 200 --lr 0.001
python -m sec_classifiers.drebin.drebin_test --dataset_dir /path/to/dataset_directory/drebin --dataset_name drebin --model "svm" --smooth "random" --cuda --sub_k 16 --epochs 200 --lr 0.01
python -m sec_classifiers.drebin.drebin_test --dataset_dir /path/to/dataset_directory/drebin --dataset_name drebin --model "dnn" --smooth "random" --cuda --sub_k 16 --epochs 200 --lr 0.001
python -m sec_classifiers.drebin.drebin_test --dataset_dir /path/to/dataset_directory/drebin --dataset_name drebin --model "svm" --smooth "hash" --cuda --sub_k 16 --epochs 200 --lr 0.01
python -m sec_classifiers.drebin.drebin_test --dataset_dir /path/to/dataset_directory/drebin --dataset_name drebin --model "dnn" --smooth "hash" --cuda --sub_k 16 --epochs 200 --lr 0.001


CUDA_VISIBLE_DEVICES=1 python run_smooth.py --output_dir=./saved_random_models --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_train --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 2 --block_size 512 --train_batch_size 2 --eval_batch_size 4 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "random" --k_random=64 --n_sampling=10 --n_estimation=10000 --seed 123456 2>&1| tee train_random_64.log
CUDA_VISIBLE_DEVICES=1 python run_smooth.py --output_dir=./saved_random_models --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_test --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 2 --block_size 512 --train_batch_size 2 --eval_batch_size 4 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "random" --k_random=64 --n_sampling=100 --n_estimation=10000 --seed 123456 2>&1| tee test_random_64.log
CUDA_VISIBLE_DEVICES=1 python run_smooth.py --output_dir=./saved_random_models --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_certify --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 2 --block_size 512 --train_batch_size 2 --eval_batch_size 4 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "random" --k_random=64 --n_sampling=100 --n_estimation=10000 --n_examples=200 --seed 123456 2>&1| tee cert_random_64.log