# CodeGPT clone detection
#CUDA_VISIBLE_DEVICES=0 python run.py --output_dir=./saved_models --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --do_train --do_test --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 2>&1| tee train.log
#CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_random_models --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --do_train --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "random" --k_random=64 --n_sampling=10 --n_estimation=10000 --seed 123456 2>&1| tee train_random_64.log
#CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_random_models --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --do_test --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "random" --k_random=64 --n_sampling=100 --n_estimation=10000 --seed 123456 2>&1| tee test_random_64.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_random_models --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --do_certify --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 2e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "random" --k_random=64 --n_sampling=100 --n_estimation=10000 --n_examples=200 --seed 123456 2>&1| tee cert_random_64.log

#CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_randdel_models --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --do_train --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "randdel" --k_random=64 --n_sampling=10 --n_estimation=10000 --seed 123456 2>&1| tee train_randdel_64.log
#CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_randdel_models --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --do_test --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "randdel" --k_random=64 --n_sampling=100 --n_estimation=10000 --seed 123456 2>&1| tee test_randdel_64.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_randdel_models --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --do_certify --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "randdel" --k_random=64 --n_sampling=100 --n_estimation=10000 --n_examples=200 --seed 123456 2>&1| tee cert_randdel_64.log

#CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_hash_models --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --do_train --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "hash" --k_random=20 --n_sampling=10 --n_estimation=10000 --seed 123456 2>&1| tee train_hash_20.log
#CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_hash_models --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --do_test --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "hash" --k_random=20 --n_sampling=100 --n_estimation=10000 --seed 123456 2>&1| tee test_hash_20.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_hash_models --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --do_certify --train_data_file=../dataset/train_sampled.txt --eval_data_file=../dataset/valid_sampled.txt --test_data_file=../dataset/test_sampled.txt --epoch 5 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "hash" --k_random=20 --n_sampling=100 --n_estimation=10000 --n_examples=200 --seed 123456 2>&1| tee cert_hash_20.log

# attack
#CUDA_VISIBLE_DEVICES=0 python attack_alert.py --output_dir=./saved_models --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --base_model=microsoft/codebert-base-mlm --csv_store_path ./attack_base_result_GA.csv --eval_data_file=../dataset/test_sampled_0_500.txt  --test_data_file=../dataset/test_sampled.txt  --block_size 512  --use_ga --eval_batch_size 32  --do_certify --smooth=none --n_examples=200 --seed 123456 2>&1| tee attack_none_GA.log
#CUDA_VISIBLE_DEVICES=0 python attack_alert.py --output_dir=./saved_random_models --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --base_model=microsoft/codebert-base-mlm --csv_store_path ./attack_base_result_random_GA.csv --eval_data_file=../dataset/test_sampled_0_500.txt  --test_data_file=../dataset/test_sampled.txt  --block_size 512  --use_ga --eval_batch_size 32  --do_certify --smooth=random --k_random=64 --n_sampling=100 --n_examples=200 --seed 123456 2>&1| tee attack_random_GA.log
#CUDA_VISIBLE_DEVICES=0 python attack_alert.py --output_dir=./saved_randdel_models --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --base_model=microsoft/codebert-base-mlm --csv_store_path ./attack_base_result_randdel_GA.csv --eval_data_file=../dataset/test_sampled_0_500.txt  --test_data_file=../dataset/test_sampled.txt  --block_size 512  --use_ga --eval_batch_size 32  --do_certify --smooth=randdel --k_random=64 --n_sampling=100 --n_examples=200 --seed 123456 2>&1| tee attack_randdel_GA.log
#CUDA_VISIBLE_DEVICES=0 python attack_alert.py --output_dir=./saved_hash_models --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --base_model=microsoft/codebert-base-mlm --csv_store_path ./attack_base_result_hash_GA.csv --eval_data_file=../dataset/test_sampled_0_500.txt  --test_data_file=../dataset/test_sampled.txt  --block_size 512  --use_ga --eval_batch_size 32  --do_certify --smooth=hash --k_random=20 --n_sampling=100 --n_examples=200 --seed 123456 2>&1| tee attack_hash_GA.log
#
#CUDA_VISIBLE_DEVICES=0 python attack_mhm.py --output_dir=./saved_models/ --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --csv_store_path ./attack_base_result_mhm.csv --base_model=microsoft/codebert-base-mlm --eval_data_file=../dataset/test_sampled_0_500.txt --test_data_file=../dataset/test_sampled.txt  --block_size 512 --eval_batch_size 32  --do_certify --original --smooth=none --n_examples=200 --seed 123456 2>&1| tee attack_none_mhm.log
#CUDA_VISIBLE_DEVICES=0 python attack_mhm.py --output_dir=./saved_random_models/ --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --csv_store_path ./attack_base_result_random_mhm.csv --base_model=microsoft/codebert-base-mlm --eval_data_file=../dataset/test_sampled_0_500.txt --test_data_file=../dataset/test_sampled.txt  --block_size 512 --eval_batch_size 32  --do_certify --original --smooth=random --k_random=64 --n_sampling=100 --n_examples=200 --seed 123456 2>&1| tee attack_random_mhm.log
#CUDA_VISIBLE_DEVICES=0 python attack_mhm.py --output_dir=./saved_randdel_models/ --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --csv_store_path ./attack_base_result_randdel_mhm.csv --base_model=microsoft/codebert-base-mlm --eval_data_file=../dataset/test_sampled_0_500.txt --test_data_file=../dataset/test_sampled.txt  --block_size 512 --eval_batch_size 32  --do_certify --original --smooth=randdel --k_random=64 --n_sampling=100 --n_examples=200 --seed 123456 2>&1| tee attack_randdel_mhm.log
#CUDA_VISIBLE_DEVICES=0 python attack_mhm.py --output_dir=./saved_hash_models/ --model_type=gpt2 --tokenizer_name=microsoft/CodeGPT-small-java-adaptedGPT2 --model_name_or_path=microsoft/CodeGPT-small-java-adaptedGPT2 --config_name=microsoft/CodeGPT-small-java-adaptedGPT2 --csv_store_path ./attack_base_result_hash_mhm.csv --base_model=microsoft/codebert-base-mlm --eval_data_file=../dataset/test_sampled_0_500.txt --test_data_file=../dataset/test_sampled.txt  --block_size 512 --eval_batch_size 32  --do_certify --original --smooth=hash --k_random=20 --n_sampling=100 --n_examples=200 --seed 123456 2>&1| tee attack_hash_mhm.log