# CodeXGLUE authorship classification
CUDA_VISIBLE_DEVICES=0 python run.py  --output_dir=./saved_models/ --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base  --number_labels 66 --do_train --do_test --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --epoch 30 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --seed 123456 2>&1| tee train_gcjpy.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_random_models/ --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_train --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --epoch 30 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "random" --k_random=128 --n_sampling=10 --n_estimation=10000 --seed 123456 2>&1| tee train_random_128.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_random_models/ --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_test --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --epoch 30 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "random" --k_random=128 --n_sampling=100 --n_estimation=10000 --seed 123456 2>&1| tee test_random_128.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_random_models/ --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_certify --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --epoch 30 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "random" --k_random=128 --n_sampling=100 --n_estimation=10000 --seed 123456 2>&1| tee cert_random_128.log

CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_randdel_models/ --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_train --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --epoch 30 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "randdel" --k_random=128 --n_sampling=10 --n_estimation=10000 --seed 123456 2>&1| tee train_randdel_128.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_randdel_models/ --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_test --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --epoch 30 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "randdel" --k_random=128 --n_sampling=100 --n_estimation=10000 --seed 123456 2>&1| tee test_randdel_128.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_randdel_models/ --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_certify --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --epoch 30 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "randdel" --k_random=128 --n_sampling=100 --n_estimation=10000 --seed 123456 2>&1| tee cert_randdel_128.log

CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_hash_models/ --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_train --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --epoch 30 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "hash" --k_random=32 --n_sampling=10 --n_estimation=10000 --seed 123456 2>&1| tee train_hash_32.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_hash_models/ --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_test --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --epoch 30 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "hash" --k_random=32 --n_sampling=100 --n_estimation=10000 --seed 123456 2>&1| tee test_hash_32.log
CUDA_VISIBLE_DEVICES=0 python run_smooth.py --output_dir=./saved_hash_models/ --model_type=roberta --config_name=microsoft/codebert-base --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --do_certify --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --epoch 30 --block_size 512 --train_batch_size 16 --eval_batch_size 32 --learning_rate 5e-5 --max_grad_norm 1.0 --evaluate_during_training --smooth "hash" --k_random=32 --n_sampling=100 --n_estimation=10000 --seed 123456 2>&1| tee cert_hash_32.log

# attack
CUDA_VISIBLE_DEVICES=0 python attack.py --output_dir=./saved_models/ --model_type=roberta --config_name=microsoft/codebert-base  --csv_store_path ./attack_base_result_GA.csv --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --use_ga --base_model=microsoft/codebert-base-mlm  --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --block_size 512 --eval_batch_size 32 --smooth=none --seed 123456 2>&1| tee attack_none_GA.log
CUDA_VISIBLE_DEVICES=0 python attack.py --output_dir=./saved_random_models/ --model_type=roberta --config_name=microsoft/codebert-base  --csv_store_path ./attack_base_result_random_GA.csv --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --use_ga --base_model=microsoft/codebert-base-mlm --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --block_size 512 --eval_batch_size 32 --smooth=random --k_random=128 --n_sampling=100 --seed 123456 2>&1| tee attack_random_GA.log
CUDA_VISIBLE_DEVICES=0 python attack.py --output_dir=./saved_randdel_models/ --model_type=roberta --config_name=microsoft/codebert-base  --csv_store_path ./attack_base_result_randdel_GA.csv --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --use_ga --base_model=microsoft/codebert-base-mlm --number_labels 66  --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --block_size 512 --eval_batch_size 32 --smooth=randdel --k_random=128 --n_sampling=100 --seed 123456 2>&1| tee attack_randdel_GA.log
CUDA_VISIBLE_DEVICES=0 python attack.py --output_dir=./saved_hash_models/ --model_type=roberta --config_name=microsoft/codebert-base  --csv_store_path ./attack_base_result_hash_GA.csv --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --use_ga --base_model=microsoft/codebert-base-mlm --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --block_size 512 --eval_batch_size 32 --smooth=hash --k_random=32 --n_sampling=100 --seed 123456 2>&1| tee attack_hash_GA.log

CUDA_VISIBLE_DEVICES=0 python mhm.py --output_dir=./saved_models/ --model_type=roberta --config_name=microsoft/codebert-base  --csv_store_path ./attack_mhm_LS.csv --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --base_model=microsoft/codebert-base-mlm --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --is_original_mhm --block_size 512 --eval_batch_size 32 --smooth=none --seed 123456 2>&1| tee attack_none_mhm.log
CUDA_VISIBLE_DEVICES=0 python mhm.py --output_dir=./saved_random_models/ --model_type=roberta --config_name=microsoft/codebert-base  --csv_store_path ./attack_mhm_random_LS.csv --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --base_model=microsoft/codebert-base-mlm --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --is_original_mhm --block_size 512 --eval_batch_size 32 --smooth=random --k_random=128 --n_sampling=100 --seed 123456 2>&1| tee attack_random_mhm.log
CUDA_VISIBLE_DEVICES=0 python mhm.py --output_dir=./saved_randdel_models/ --model_type=roberta --config_name=microsoft/codebert-base  --csv_store_path ./attack_mhm_randdel_LS.csv --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --base_model=microsoft/codebert-base-mlm --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --is_original_mhm --block_size 512 --eval_batch_size 32 --smooth=randdel --k_random=128 --n_sampling=100 --seed 123456 2>&1| tee attack_randdel_mhm.log
CUDA_VISIBLE_DEVICES=0 python mhm.py --output_dir=./saved_hash_models/ --model_type=roberta --config_name=microsoft/codebert-base  --csv_store_path ./attack_mhm_hash_LS.csv --model_name_or_path=microsoft/codebert-base --tokenizer_name=roberta-base --base_model=microsoft/codebert-base-mlm --number_labels 66 --train_data_file=../dataset/processed_gcjpy/train.txt --eval_data_file=../dataset/processed_gcjpy/valid.txt --test_data_file=../dataset/processed_gcjpy/valid.txt --is_original_mhm --block_size 512 --eval_batch_size 32 --smooth=hash --k_random=32 --n_sampling=100 --seed 123456 2>&1| tee attack_hash_mhm.log